// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pcvpfoemuvpchazbcjkj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBjdnBmb2VtdXZwY2hhemJjamtqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3NDc3MTYsImV4cCI6MjA2NjMyMzcxNn0.mPGs8mzqCyvO3jr6Z9PF0mnV6yM89aPPsijPJX0vEvY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);